resources:
  - name: artifactory_go
    type: GitRepo
    configuration:
      path: vijayreddy1991/artifactory-go-example
      branches:
        include: GoBuild
      gitProvider: vijay_github

pipelines:
  - name: go_build
    steps:
      - name: build_go
        type: GoBuild
        configuration:
          sourceLocation: .
          repository: vijay-go-local
          outputLocation: /tmp/dist
          outputFile: hello_gb
          inputResources:
            - name: artifactory_go
          integrations:
            - name: varsha_artifactory
        execution:
          onStart:
            - wget https://dl.google.com/go/go1.12.5.linux-amd64.tar.gz
            - sudo tar -C /usr/local -xzf go1.12.5.linux-amd64.tar.gz
            - export PATH=$PATH:/usr/local/go/bin
            - go version
              
            
            
            
