resources:
  - name: artifactory_go
    type: GitRepo
    configuration:
      path: vijayreddy1991/artifactory-go-example
      branches:
        include: GoBuild
      gitProvider: vijay_github
      
  - name: go_build_info_publish1
    type: BuildInfo
    configuration:
      sourceArtifactory: varsha_artifactory
      buildName: go_example_build_publish1
      buildNumber: 1
      
  - name: unsigned_release_bundle_go_publish1
    type: ReleaseBundle
    configuration:
      sourceArtifactory: varsha_artifactory
      name: go_test_bundle
      version: v1.6
      
  - name: signed_release_bundle_go_publish1
    type: ReleaseBundle
    configuration:
      sourceArtifactory: varsha_artifactory
      name: go_test_bundle
      version: v1.6
      
  - name: promoted_go_build_info_go_publish1
    type: BuildInfo
    configuration:
      sourceArtifactory: varsha_artifactory
      buildName: promote_go_build_publish1
      buildNumber: 1
      
  - name: distribution_rule_go_publish1
    type: DistributionRule
    configuration:
      sourceArtifactory: varsha_artifactory
      cityName: "*"
      serviceName: "*"
      siteName: "*"
      countryCodes:
        - CN


pipelines:
  - name: go_build
    steps:
      - name: build_go
        type: GoBuild
        configuration:
          sourceLocation: .
          repository: vijay-go-local
          outputLocation: /tmp/dist
          outputFile: hello
          inputResources:
            - name: artifactory_go
          integrations:
            - name: varsha_artifactory
        execution:
          onStart:
            - wget https://dl.google.com/go/go1.12.5.linux-amd64.tar.gz
            - sudo tar -C /usr/local -xzf go1.12.5.linux-amd64.tar.gz
            - export PATH=$PATH:/usr/local/go/bin
            - go version
            
      - name: publish_build_info
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: build_go
          outputResources:
            - name: go_build_info_publish1

      - name: promote_build_go
        type: PromoteBuild
        configuration:
          targetRepository: promoted_go_test
          integrations:
            - name: varsha_artifactory
          inputResources:
            - name: go_build_info_publish1
          outputResources:
            - name: promoted_go_build_info_go_publish1
            
      - name: bundle_go_publish1
        type: CreateReleaseBundle
        configuration:
          dryRun: false
          description: "This is to test GoPublishModule -> PublishBuildInfo -> Promote -> CreateRelease -> Sign -> Distribute pipeline chain"
          releaseBundleName: go_publish_test_build
          releaseBundleVersion: v1.6
          sign: false
          inputResources:
            - name: promoted_go_build_info_go_publish1
          outputResources:
            - name: unsigned_release_bundle_go_publish1
            
      - name: sign_release_bundle_go_publish1
        type: SignReleaseBundle
        configuration:
          inputResources:
            - name: unsigned_release_bundle_go_publish1
          outputResources:
            - name: signed_release_bundle_go_publish1
            
      - name: distribute_signed_release_bundle1
        type: DistributeReleaseBundle
        configuration:
          dryRun: false
          inputResources:
            - name: signed_release_bundle_go_publish1
            - name: distribution_rule_go_publish1
          integrations:              
            - varsha_artifactory
            
              
            
            
            
